# Generated by Django 3.2 on 2021-04-17 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email_address', models.EmailField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_order', models.CharField(default='0', max_length=20)),
                ('unit_number', models.CharField(blank=True, max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobTrackingApp.client')),
            ],
        ),
    ]
