# Generated by Django 3.2 on 2021-04-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('unit_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_order', models.CharField(default='0', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobTrackingApp.client')),
            ],
        ),
    ]
