# Generated by Django 3.2 on 2021-04-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='unit_number',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
