# Generated by Django 3.2 on 2021-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='work_order',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
