# Generated by Django 3.2 on 2021-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0002_auto_20210501_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
