# Generated by Django 3.2 on 2021-04-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0002_auto_20210416_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='work_order',
            field=models.CharField(default='0', help_text='optional', max_length=20),
        ),
    ]
