# Generated by Django 3.2 on 2021-04-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0003_alter_scheduleevent_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='work_order',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
