# Generated by Django 3.2 on 2021-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0004_alter_scheduleevent_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
