# Generated by Django 3.2 on 2021-05-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0005_alter_scheduleevent_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleevent',
            old_name='time',
            new_name='duration',
        ),
    ]
