# Generated by Django 3.2 on 2021-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0006_rename_time_scheduleevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
