# Generated by Django 3.2 on 2021-05-01 20:55

import JobTrackingApp.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTrackingApp', '0008_alter_scheduleevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='duration',
            field=models.CharField(blank=True, max_length=100, validators=[JobTrackingApp.validations.validate_duration]),
        ),
    ]
